/** A JSDoc Comment to explain what the function does.
 * Home: The Landing page of the web app
 * @return {JSX.Element} The JSX Code for the Home Page
 */
import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

import { Header } from '@/components/Header/Header'

import { Footer } from '@/components/Footers/index'

import { ContactUs } from '@/components/Base/emailjsbase'
import MessageForm from '@/components/Base/MessageForm'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* <Header links={links} /> */}
			<Header />

			<ContactUs />
			<MessageForm />
			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.tsx</code>
				</p>
				<div className={styles.cardContainer}>
					<div className={styles.card}>
						<div className={styles.title}>Card 1</div>
						<div className={styles.description}>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
							eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</div>
					</div>

					<div className={styles.card}>
						<div className={styles.title}>Card 2</div>
						<div className={styles.description}>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
							eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</div>
					</div>

					<div className={styles.card}>
						<div className={styles.title}>Card 3</div>
						<div className={styles.description}>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
							eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</div>
					</div>
				</div>
			</main>
			<Footer />
		</div>
	)
}

export default Home
